name: Deploy Jekyll Resume to GitHub Pages

on:
  push:
    branches: ["main"] # Changed from master to main (GitHub default)
  workflow_dispatch:

permissions:
  contents: write # Changed from read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1 # Updated from SHA reference
        with:
          ruby-version: '3.1' # Updated from 3.0
          bundler-cache: true
          cache-version: 1 # Incremented from 0

      - name: Build Jekyll Site
        run: bundle exec jekyll build --destination ./public
        env:
          JEKYLL_ENV: production

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # Updated from v1 to v2
